apiVersion: apps/v1
kind: Deployment
metadata:
 name: filemanager
 namespace: default 
spec:
 replicas: 3
 selector:
  matchLabels:
   app: filemanager
 template:
  metadata:
   labels:
    app: filemanager
  spec:
   containers:
   - name: filemanager
     image: docker.io/jbazte/filemanager:1.3
     volumeMounts:
     - mountPath: /home/ubuntu/prueba
       name: directorio-prueba
   volumes:
   - name: directorio-prueba
     hostPath:
      path: /home/ubuntu/compartido
      type: Directory