apiVersion: v1
kind: Service
metadata:
 name: filemanager-entrypoint
 namespace: default
spec:
 type: NodePort
 selector:
  app: filemanager
 ports:
 - port: 30003
   targetPort: 30003
   nodePort: 30003
 externalTrafficPolicy: Cluster
